language: node_js
node_js:
  - node
cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp-cli

script:
  - gulp ci

notifications:
  slack:
    rooms:
      - mmisw:yEUK01ro6HVvhRbkq9a2Y3df
      - esip-all:I3mBBBC9PChg913QUU5OUMlf
